In [2]:
# pip install numpy
# importing numpy library
import numpy as np

In [3]:
# create a numpy array from python list
x = np.array([1, 3, 5, 6])
print(x)

# Check the shape of the array
print(x.shape)

# Print the size of the array
# It is the total number of elements in the array
print(x.size)

# Check the dimension of the array
print(x.ndim)

[1 3 5 6]
(4,)
4
1


In [4]:
# Create arrays from scratch
# Create an empty array
x = np.empty([3, 5], dtype = np.float32) # You can change the Datatype of the array
print(x.dtype)

# Create a matrix of zeros
y = np.zeros([3, 5], dtype = 'int')
print(y)

# Create a matrix of ones
z = np.ones([3, 5])
print(z)

# Create a 3*5 array filled with 3.141
m = np.full((3, 5), 3.141)
print(m)

float32
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 3.141  3.141  3.141  3.141  3.141]
 [ 3.141  3.141  3.141  3.141  3.141]
 [ 3.141  3.141  3.141  3.141  3.141]]


In [5]:
# Create array object using numpy with step size 2 and range between 0 to 20
x = np.arange(0, 20, 2)
print(x)

# Create an array of five values evenly spaced between 1 and 4
y = np.linspace(2, 6, 3)
print(y)

# create a 3*3 array of uniformly distributed random values between 0 and 1
z = np.random.rand(3, 3) 
# remember you can also use np.random.random((3, 3))
# The only difference is how it handles the arguments that's it!
print('The uniform distribution is =\n',z)

# You can also create random matrix from normal distribution
# With specific standard deviation and mean value

normal_dist = np.random.normal(0, 1, (3,3))
print('The normal distribution is =\n ',normal_dist)


# We can also create the random matrix of integers
# Lets say we want to create a random matrix between number 1 to 5 
# Here 5 is inclusive i.e. [1,5] or (0,6) or [1,6)

int_mat = np.random.randint(0, 6, (3, 3))
print('The integer matrix is = \n',int_mat)
print(int_mat.shape)
print(int_mat.ndim)
print(int_mat.size)

[ 0  2  4  6  8 10 12 14 16 18]
[ 2.  4.  6.]
The uniform distribution is =
 [[ 0.82744206  0.96036858  0.37807274]
 [ 0.83823679  0.1856934   0.5480639 ]
 [ 0.65964391  0.24540786  0.30501498]]
The normal distribution is =
  [[-1.28776012 -0.5305137  -1.01292306]
 [-1.55436375 -0.04083867 -0.70901341]
 [-0.52283298  2.4116772   0.43565139]]
The integer matrix is = 
 [[2 4 4]
 [5 2 5]
 [0 0 3]]
(3, 3)
2
9


In [6]:
# you can explicitly convert or cast an array from one datatype to another 
# using ndarray's astype method

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

arr1 = arr.astype('float32') # This is not an inplace function
print(arr1.dtype)

arr2 = np.array([12.4, 9.6, 4.5, -2.6, 0.5, 9.8]) 
print(arr2.dtype)

arr3 = arr2.astype('int32') # It will convert float to integers and round the values
print(arr3)
print(arr3.dtype)

int32
float32
float64
[12  9  4 -2  0  9]
int32


In [ ]:
# If you are trying to convert one dtype to another dtype
# If it is not possible then it will raise ValueError

try:
    arr  = np.array(['1.2', '3', 'ram'], dtype = 'string_')
    print(arr.dtype)
    arr1 = arr.astype(np.int32)
    
except ValueError:
    print('Cant convert the string to intgers')
    
# NOTE:
# Calling astype always create a new array (a copy of the data), even if the new dtype is the 
# same as the old dtype

In [ ]:
# Create a range of numpy arrays with step size
x = np.arange(0, 10, 2)
print(x)

Python for loops are very slow and large dataset can be time consuming. To avoid these for loops numpy supports vectorization.

In [ ]:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
# we can do the arithmatic operation on these arrays
# for the same size it will do the element wise opertations
print('The array is = \n', arr)
print('Multiplication of two arrays=\n',arr*arr)

# If the two arrays have different shape then you can use np.dot function
arr1 = arr.T # We are taking the transpose 
print('The shape of the array after transpose is = ', arr1.shape)
print('The multiplication of two arrays = \n', arr.dot(arr1))

print('Subtraction of two arrays = \n', arr-arr)
print('Square root of the array is = \n', arr**0.5)

In [ ]:
# You can also compare between two arrays of same size
# The o/p is a boolean matrix

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr1 = np.array([
    [1, 2, 3],
    [7, 8, 9]
])

print('Comparing two numpy arrays of same size if greater\n', arr > arr1)
print('Comparing two numpy arrays of same size if equal\n', arr == arr1)

Numpy Indexing and slicing

In [ ]:
# one dimensional array is like a python list
arr = np.arange(10)
print(arr[5])
print(arr[2:5])
# we can assign new values
arr[5:8] = 12
print(arr)

The difference between Python list and numpy ndarray is that modification in Numpy's slicing array will be reflected in the original array. Let's see an example of this-

In [7]:
arr = np.arange(10) # Created an array of 10 elements
arr_slice = arr[5:8] # We have a slice of the main array
print(arr_slice)
arr_slice[1] = 32
print(arr) # You can see the change in the original array

# The bare slice [:], will assign to all values in an array
arr_slice[:] = 64
print(arr)

# If you want an explicit copy of the array then use .copy()
# Remember the difference between copy and deepcopy in Python
# Your normal copy is shallow copy whereas the deepcopy actually creates a new copy 

new_arr = arr[5:8].copy()
print(new_arr)
new_arr[:] = 32
print(arr)

[5 6 7]
[ 0  1  2  3  4  5 32  7  8  9]
[ 0  1  2  3  4 64 64 64  8  9]
[64 64 64]
[ 0  1  2  3  4 64 64 64  8  9]


In [ ]:
# Let's see some more about the high dimensional arrays
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# If we want to get a 1D array from this 2D array then we can use slicing

slice_arr2d = arr2d[1]
print('The 1D array is = \n',slice_arr2d)

# If we want to get the specfic element of the array 

ele_arr2d = arr2d[1][1]
# ele_arr2d = arr2d[1, 1] # same as the above
print('The middle element of the 2D array is = \n', ele_arr2d)

In [8]:
# Let's see an example of a 3D array slicing

arr3d = np.array([
    [[1, 2, 3],
    [4, 5, 6]],
    [[7, 8, 9],
    [10, 11, 12]]
])
# print(arr3d)
print('Print the shape of the array ',arr3d.shape)
print(arr3d[0]) # It will give you the first (2*3) array 

#we can do the assignment to the small slice of the main array

slice_arr3d = arr3d[0]
slice_arr3d = 42
print(slice_arr3d)

Print the shape of the array  (2, 2, 3)
[[1 2 3]
 [4 5 6]]
42


In [9]:
# We want the row [7, 8, 9] from this list
arr3d = np.array([
    [[1, 2, 3],
    [4, 5, 6]],
    [[7, 8, 9],
    [10, 11, 12]]
])
print(arr3d[1][0])
# print(arr3d[1,0]) # Same as above 

[7 8 9]


In [16]:
# Setting values in an array using condition

data = np.random.randn(3, 5)
print('The data we have created is = \n', data)
data[data<0]=0 # Assigning all the negative values to zero
print('Data after assignment is = \n', data)

The data we have created is = 
 [[-1.93228222 -1.34525564  0.35365754 -0.82597225  0.13894107]
 [-0.34583821  0.60731664 -0.40770129 -1.23180474 -2.05437347]
 [ 3.51063427 -0.50849332 -1.00942286 -0.84832409 -3.20690815]]
Data after assignment is = 
 [[ 0.          0.          0.35365754  0.          0.13894107]
 [ 0.          0.60731664  0.          0.          0.        ]
 [ 3.51063427  0.          0.          0.          0.        ]]


In [ ]:
# How to fill the elements in an empty matrix
emp_mat = np.empty([5, 5])
# print(emp_mat)

for i in range(5):
    for j in range(5):
        emp_mat[i][j] = i*j
print(emp_mat)

# If we want to choose multiple rows from emp_array

print(emp_mat[[2, 0, 3]]) # Simply pass a list or ndarray of integers specifying the desired order

In [ ]:
# We can also reshape the array using reshape function
x = np.arange(16)
x.reshape((4, 4))

In [ ]:
# We can use fancy indexing to choose and shuffle the matrix the way we want
x = np.arange(32).reshape(8, 4)
print(x)

# Let's say we want to choose the selected rows and selected coloumns from x
# Selecting rows 1, 5, 7, 2 and from all the 
print('The new array we have created is = \n', x[[1, 5, 7, 2]][:,[0, 3, 1, 2]]) 

# Note - Fancy indexing is not in place like normal slicing, it creates the new array

In [ ]:
# Transposing arrays
# This is not an inplace function

arr = np.random.rand(5, 3)
print(arr.shape)
new_arr = arr.T
print(new_arr.shape)
print(arr.shape)

# We can do inner matrix multiplication using np.dot function

mul_mat = np.dot(arr, new_arr)
print(mul_mat.shape)

In [ ]:
# We can concatenate more than two arrays using numpy

x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
z = np.array([1, 2, 4, 5])

print(np.concatenate([x, y, x]))

# We can concatenate two dimensional arrays as well

x = np.array([[1, 2, 3],[4, 5, 6]])
print('We are concatenating along rows = ', np.concatenate([x, x]))
print('We are concatenating along coloumns = \n', np.concatenate([x, x], axis = 1))

In [ ]:
# We can concatenate two different shapes of matrix
# along vertical axis -> we will use vstack
# ALong horizontal axis -> we will use hstack

x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6], [7, 8, 9]])

print('After vertical stacking = \n',np.vstack([x, grid]))

y = np.array([[10], [11]])
print('After horizontal stacking = \n',np.hstack([grid, y]))

In [ ]:
# Difference between array and asarray in numpy

x = np.matrix(np.ones([3, 3]))
print(x)

# The main difference is that array (by default) will make a copy of the object, 
# while asarray will not unless necessary.
# If we want to change the 3rd row of the matrix to 2
np.array(x)[2] = 2
print('After the array conversion = \n', x) # Since the changes are made in a copy not in x

np.asarray(x)[2] = 2
print('After the asarray conversion = \n', x) # This is an inplace operation